# Generated by Django 3.1.1 on 2020-09-03 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20200903_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='overveiw',
            new_name='overview',
        ),
    ]
